config/routes.rb
Rails.application.routes.draw do

  resources :item_types
  resources :items
  root 'items#index'
  

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :item_type
	validates :title, presence: true

	def completed?
		completed_on != nil
    end



    def image_fetcher
    	self.image_url = ImageFetcher.new.fetch(self.title)
    	save
    end

	def to_param
		"#{id}-#{title.parameterize}"
	end


end

app/models/item_type.rb
class ItemType < ActiveRecord::Base
	 has_many :items

	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@items = Item.all
	end

	def new
		@item = Item.new
	end

	def edit
		@item = Item.find(params[:id])
	end

	def create
    @item = Item.new(item_params)
    if @item.save
      @item.image_fetcher
      redirect_to items_path
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])

    if @item.update_attributes(item_params)
      @item.image_fetcher
      redirect_to items_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  def item_params
    params.require(:item).permit(:title, :completed_on, :item_type_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |i| %>
  <% if @item.errors.any? %>
    <div class='errors'>
      <h2>Oh no, errors!</h2>
      <% @item.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>


<div class='field'>
    <%= i.label :item_type, 'What type of item is this?' %>
    <%= i.collection_select :item_type_id, ItemType.all, :id, :name %>
</div>

 <div class='field'>
    <%= i.label :title %>
    <%= i.text_field :title %>
  </div>

   <div class='field'>
    <%= i.label :completed_on, 'When was this completed?' %>
    <%= i.date_select(:completed_on, order:[:day, :month, :year]) %>

    <div class='field'>
    <%= i.submit 'Save' %>
  </div>
</div>

<% end %>

app/views/items/edit.html.erb
<h1>Edit Entry</h1>

<%= render 'form' %>

<%= end %>

app/views/items/index.html.erb
<h1> Melissa's Library </h1>


  <%= link_to 'New Item', new_item_path %>

  <%=@items.each do |item| %>
  <%=item.item_type.name%> <%=item.title%>

  <%=image_tag(item.image_url)%>
  <br>
  <%=item.completed?? h("Completed") : h("NotCompleted") %>

  <br>

  <%= link_to 'Edit', edit_item_path(item) %>

  <%= link_to 'Delete', item_path(item), method: :delete %>
  </p>



<%end%>

app/views/items/new.html.erb
<h1>New Entry</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Liibrary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>